In [1]:
import numpy as np

In [2]:
l1=[1,2,3,4]

In [3]:
np.array(l1)

array([1, 2, 3, 4])

In [4]:
l2= list(range(1,13))

In [5]:
l2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [6]:
a= np.array(l2)

In [7]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
a.shape, a.ndim , a.size

((12,), 1, 12)

In [11]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
a2=a.reshape(2,6)

In [16]:
a2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [17]:
a2.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
a1= np.random.randint(1,9,size=(3,3))

In [32]:
a1

array([[1, 7, 5],
       [2, 7, 8],
       [4, 1, 4]], dtype=int32)

In [20]:
a1.shape, a1.ndim,a1.size

((3, 2), 2, 6)

In [21]:
a2= np.random.randint(1,9,size=(3,3))

In [22]:
a2

array([[7, 5, 1],
       [8, 6, 8],
       [8, 3, 7]], dtype=int32)

In [23]:
a2.shape, a2.ndim,a2.size

((3, 3), 2, 9)

In [33]:
a1+a2

array([[ 8, 12,  6],
       [10, 13, 16],
       [12,  4, 11]], dtype=int32)

In [34]:
a1*a2

array([[ 7, 35,  5],
       [16, 42, 64],
       [32,  3, 28]], dtype=int32)

In [35]:
a1/a2

array([[0.14285714, 1.4       , 5.        ],
       [0.25      , 1.16666667, 1.        ],
       [0.5       , 0.33333333, 0.57142857]])

In [36]:
a1-a2

array([[-6,  2,  4],
       [-6,  1,  0],
       [-4, -2, -3]], dtype=int32)

In [37]:
b1= np.random.randint(1,9,(3,2))

In [38]:
b1.size,b1.ndim,b1.shape

(6, 2, (3, 2))

In [39]:
a2

array([[7, 5, 1],
       [8, 6, 8],
       [8, 3, 7]], dtype=int32)

In [40]:
b1.dot(a2)

ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [41]:
b2= np.random.randint(1,9,(2,3))

In [42]:
b2.size,b2.shape, b2.ndim

(6, (2, 3), 2)

In [44]:
c=b2.dot(a2)

In [45]:
c

array([[ 71,  41,  61],
       [105,  65,  59]], dtype=int32)

In [47]:
c.ndim,c.shape

(2, (2, 3))

In [48]:
b1

array([[7, 7],
       [4, 1],
       [6, 3]], dtype=int32)

In [49]:
a2.dot(b1)

array([[ 75,  57],
       [128,  86],
       [110,  80]], dtype=int32)

In [50]:
b1.dot(a2)

ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [51]:
b1.dot(a2.T)

ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [53]:
a2.max()

np.int32(8)

In [54]:
a2.min()

np.int32(1)

In [55]:
a2.sum()

np.int64(53)

In [56]:
a2.max(axis=0)

array([8, 6, 8], dtype=int32)

In [57]:
a2.max(axis=1)

array([7, 8, 8], dtype=int32)

In [59]:
a2.mean()

np.float64(5.888888888888889)

In [60]:
b3= np.random.randint(1,20,size=(3,7))

In [63]:
b3.shape,b3.size,b3.ndim

((3, 7), 21, 2)

In [64]:
b3

array([[15, 18,  9,  5, 12, 13, 13],
       [15, 11,  4,  6, 10, 15, 14],
       [ 4,  3,  4, 16, 16, 14,  1]], dtype=int32)

In [65]:
b3.T

array([[15, 15,  4],
       [18, 11,  3],
       [ 9,  4,  4],
       [ 5,  6, 16],
       [12, 10, 16],
       [13, 15, 14],
       [13, 14,  1]], dtype=int32)

In [72]:
a=int(input())

In [73]:
a

12

In [74]:
type(a)

int