In [1]:
import numpy as np

In [2]:
l= list(range(10))

In [3]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
arr=np.array(l)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.ndim

1

In [9]:
arr.size

10

In [10]:
arr.shape

(10,)

In [12]:
a=np.array(19)

In [13]:
a

array(19)

In [14]:
type(a)

numpy.ndarray

In [15]:
a.size

1

In [16]:
arr.max()

np.int64(9)

In [17]:
arr.min()

np.int64(0)

In [18]:
arr.sum()

np.int64(45)

In [19]:
arr.mean()

np.float64(4.5)

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr.dtype

dtype('int64')

In [22]:
aar1= np.array([1,2,3,4],dtype=float)

In [23]:
aar1

array([1., 2., 3., 4.])

In [24]:
aar1.dtype

dtype('float64')

In [25]:
arr.dtype

dtype('int64')

In [26]:
arr2=arr.astype(float)

In [27]:
arr2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [28]:
arr2.dtype

dtype('float64')

In [29]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
arr+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
arr=5

In [33]:
arr=np.array(l)

In [34]:
arr - 19

array([-19, -18, -17, -16, -15, -14, -13, -12, -11, -10])

In [35]:
arr/10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [36]:
arr3 =np.ones(10)

In [38]:
arr3

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [39]:
arr + arr3

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [40]:
arr4= np.random.randint(1,10,5)

In [41]:
arr4

array([1, 6, 4, 5, 6], dtype=int32)

In [42]:
arr.dtype

dtype('int64')

In [43]:
arr4.ndim

1

In [46]:
arr5= np.random.randint(1,10,(5,9))

In [47]:
arr5

array([[1, 5, 9, 8, 7, 2, 9, 7, 4],
       [1, 7, 5, 7, 7, 9, 8, 2, 9],
       [2, 3, 2, 8, 3, 3, 8, 6, 5],
       [6, 5, 9, 1, 1, 7, 3, 2, 3],
       [1, 3, 3, 9, 9, 9, 8, 6, 7]], dtype=int32)

In [54]:
arr6= np.arange(10,50,5)

In [55]:
arr6

array([10, 15, 20, 25, 30, 35, 40, 45])

In [56]:
arr6.shape,arr6.ndim

((8,), 1)

In [59]:
a1d= np.array([1,2,3,4,5])

In [63]:
a2d= np.array([
    
               [1,2,3,4],
               [5,4,3,5]
               
               ])

In [64]:
a2d

array([[1, 2, 3, 4],
       [5, 4, 3, 5]])

In [66]:
a3d = np.array(
               [
                [
                [1,2,3],
                 [4,5,6]
                 ],
                
                [
                    [7,8,9],
                 [10,11,12]
                 ]
                ]
                )

In [72]:
a3d.ndim,a3d.shape

(3, (2, 2, 3))

In [67]:
a3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [71]:
a2d.ndim,a2d.shape

(2, (2, 4))

In [70]:
a3d.ndim,a3d.shape

(3, (2, 2, 3))

In [74]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [76]:
np.full((4,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [77]:
np.random.random((3,4))

array([[0.79131603, 0.81435003, 0.59777619, 0.67429583],
       [0.65701309, 0.4887138 , 0.50122164, 0.25584692],
       [0.25591336, 0.353522  , 0.91812497, 0.01468078]])

In [83]:
a=np.arange(12)

In [84]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [86]:
a.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
a.reshape((4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [89]:
a.reshape((2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [91]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [95]:
np.eye(9,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]])